[package]
name = "game-of-life"
version = "0.2.0"
authors = ["Caspar Krieger <git@asparck.com>"]
edition = "2018"

[workspace]

[dependencies]
conway = {path = "conway"}
sdl2 = "*"
structopt = "*"
clap = "*"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
